### ISSUE TITLE
Where is my credit ? 

### ISSUE THREAD

**Issue by appujet** [vaibhav-chauchan/lavalink-vps#1]
Are you copied but where is my credit ?

**Comment by Jethalal1234** [comment]
Hello @brblacky Would you give us your Discord username? We shall contact you soon in your DM's.

**Comment by Jethalal1234** [comment]
I also helped @vaibhav-chauchan in developing this, we shall talk about the credits in DM's. Please Dm me on </Jethalal>#9999.

**Comment by appujet** [comment]
https://github.com/brblacky/lavalink-server

What is difference this and your code 

just removed one line bruh
